Fix issues related to AuthSignIn page
microg/GmsCore pull request #2585
Opened 2024-10-16 03:52 UTC by DaVinci9196

Fixed the issue that the account selection page is not fully displayed in landscape mode.
![image](https://github.com/user-attachments/assets/e7629aad-a8e6-4551-9b3d-516d3ea76e3e)

2024-11-11 03:09 UTC, mar-v-in commented
I think it would be better to have two layout files and have the resource manager pick the appropriate layout file based on viewport size.

2024-11-11 06:15 UTC, DaVinci9196 commented
> I think it would be better to have two layout files and have the resource manager pick the appropriate layout file based on viewport size.

Changed

2024-11-12 23:32 UTC, mar-v-in requested changes

2024-11-12 23:32 UTC, mar-v-in commented on play-services-core/src/main/res/layout/signin_picker.xml
Please undo the changes in this file (as they're all just formatting, it showing up in the history will only cause confusion)

2024-11-12 23:32 UTC, mar-v-in commented on play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AuthSignInActivity.kt
> +    private lateinit var accountManager: AccountManager
It would be better to not keep this reference but instead just re-invoke `getSystemService<AccountManager>()` in `initView()`.

2024-11-12 23:32 UTC, mar-v-in commented on play-services-core/src/main/kotlin/org/microg/gms/auth/signin/AuthSignInActivity.kt
> +    private fun initView(){
There's a space missing between `)` and `{`.

2024-11-12 23:32 UTC, mar-v-in commented on play-services-core/src/main/res/layout-land/signin_picker.xml
I think it would be better to base the decision on the screen width (using `layout-w600dp`) instead of orientation (`layout-land`) as orientation doesn't tell anything about screen width and would only confuse users if e.g. the screen is almost square (like on the inner screen of some foldables)

2024-11-13 01:49 UTC, DaVinci9196 commented
@mar-v-in Modified

2024-11-13 02:26 UTC, mar-v-in approved these changes

2024-11-16 22:13 UTC, merged