DynamicLink: Added network connection conversion processing
microg/GmsCore pull request #2662
Opened 2024-12-04 08:47 UTC by DaVinci9196

The test found that in two scenarios, obtaining the DynamicLinksService getDynamicLink method would cause the application to display abnormally.
Scenario 1: Clicking the link shared by SoundCloud on WhatsApp will result in a black screen.
Scenario 2: When opening the link shared by Google Photos, WhatsApp will display that the corresponding sharing link cannot be found.

Improve the createShortDynamicLink method to fix the problem of no response when clicking share in the app.
e.g. com.cyberdavinci.gptkeyboard

2025-03-31 21:20 UTC, mar-v-in requested changes

2025-03-31 21:20 UTC, mar-v-in commented on play-services-base/core/build.gradle
> +    api project(':play-services-core-proto')
`play-services-base-core` should not depend on `play-services-core-proto`. proto specifications in `play-services-core-proto` are only meant to be consumed in `play-services-core`. Better keep the `datamixer.proto` and `DynamicLinkUtils` in `play-services-appinvite/core`, where they can be accessed from `play-services-core` if needed.

2025-04-01 02:23 UTC, DaVinci9196 commented on play-services-base/core/build.gradle
> +    api project(':play-services-core-proto')
Optimized

2025-04-14 17:05 UTC, mar-v-in approved these changes

2025-04-14 18:00 UTC, merged